{% set name = "pytrait" %}
{% set version = "0.0.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pytrait-{{ version }}.tar.gz
  sha256: 5d71b00af2a400496d5c3354ded97679dca12ce1a1926de4240129363053dd2a
  patches:
    - 0001-remove-slash.patch

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}

test:
  imports:
    - pytrait
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/xrudelis/pytrait
  summary: Rust-like traits for Python3
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
